# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth

on:
  workflow_dispatch:
  schedule:
     - cron: '0 16 */2 * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        PAT: ${{ secrets.PAT }}
    steps:
      - uses: actions/checkout@v1
        
      - name: Clone
        run: |
          git clone https://github.com/Sunert/Scripts.git ~/Scripts
      - name: Pull
        run: |
          git clone "https://" + ${{ secrets.PAT }} + "@github.com/T-playground/test_sync.git" ~/test
          sudo cp ~/Scripts/Task/youth.js ~/test/youth.js
          cd ~/test
          git add ./youth.js
          git commit
          git push
        
