# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: youth

on:
  workflow_dispatch:
  schedule:
     - cron: '0 16 */2 * *'
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - uses: actions/checkout@v1
        
      - name: Clone
        run: |
          git clone https://github.com/Sunert/Scripts.git ~/Scripts
      - name: Pull
        run: |
          git clone ${{ secrets.PPSSAA }} ~/test_sync
          sudo cp ~/Scripts/Task/youth.js ~/test_sync/youth.js
      - name: Pull2
        run: |
          cd ~/test_sync
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.NAME }}"
          git add ./youth/youth.js
          git commit -m "Auto update"
          git push
        
